title:              DevDawn Blog
short_title:        DevDawn
email:              wojciech185sz@gmail.com
code:               f/mpzenvnz
description:        "Exploring effective software engineering solutions and best practices"
author:             Wojciech Szlosek
baseurl:            "/DevDawn"
url:                "https://wszlosek.github.io"

# Social Profiles
twitter_username:   szlosek_
github_username:    wszlosek
facebook_username:
instagram_username:  
linkedin_username:  wojciech-szlosek

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-K3C4RBPQBZ # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
